// Generated by CoffeeScript 1.6.2
(function() {
  var AMBIGUOUS_DIGITS, AMBIGUOUS_SYMBOLS, DIGITS, LETTERS, SYMBOLS, crypto, generate, merge, random;

  crypto = require('./crypto');

  LETTERS = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';

  SYMBOLS = '!<>[]{}()=+@#$%^&*.,?/;:';

  DIGITS = '0123456789';

  AMBIGUOUS_SYMBOLS = '`~-_|\'\"';

  AMBIGUOUS_DIGITS = '015';

  random = function(chars, length) {
    var char, i, index, len, string, _i;

    if (length < 0) {
      return '';
    }
    len = chars.length;
    string = '';
    for (i = _i = 0; _i < length; i = _i += 1) {
      index = Math.floor(crypto.randomValue() * len);
      char = chars[index];
      string += char;
    }
    return string;
  };

  merge = function(a, b) {
    var i, len, pos, _i, _ref;

    len = a.length;
    for (i = _i = 0, _ref = b.length; _i < _ref; i = _i += 1) {
      pos = Math.floor(crypto.randomValue() * len);
      a = a.slice(0, pos) + b[i] + a.slice(pos);
    }
    return a;
  };

  generate = {
    random: function(length, digits, symbols) {
      var chars, len, password;

      if (length == null) {
        length = 20;
      }
      if (digits == null) {
        digits = 0;
      }
      if (symbols == null) {
        symbols = 0;
      }
      chars = LETTERS;
      len = {};
      len.letters = length - digits - symbols;
      len.digits = digits;
      len.symbols = symbols;
      len.chars = chars.length;
      password = random(LETTERS, len.letters);
      if (len.digits !== 0) {
        digits = random(DIGITS, len.digits);
      }
      if (len.symbols !== 0) {
        symbols = random(SYMBOLS, len.symbols);
      }
      return console.log(password, digits, symbols);
    },
    merge: merge
  };

  module.exports = generate;

}).call(this);
