// Generated by CoffeeScript 1.6.3
(function() {
  var $,
    __slice = [].slice;

  $ = (function() {
    function $(query) {
      return document.querySelector(query);
    }

    $.find = function(parent, query) {
      return parent.querySelector(query);
    };

    $.findAll = function(parent, query) {
      return parent.querySelectorAll(query);
    };

    $.create = function(tag) {
      return document.createElement(tag);
    };

    $.append = function(el, parent) {
      if (parent == null) {
        parent = document.body;
      }
      return parent.appendChild(el);
    };

    $.prepend = function(el) {
      return document.body.insertBefore(el, document.body.firstChild);
    };

    $.tag = function(tag) {
      return document.getElementsByTagName(tag);
    };

    $.id = function(id) {
      return document.getElementById(id);
    };

    $["class"] = function(className) {
      return document.getElementsByClassName(className);
    };

    $.all = function(query) {
      return document.querySelectorAll(query);
    };

    $.addClass = function() {
      var className, el, _ref;
      el = arguments[0], className = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      return (_ref = el.classList).add.apply(_ref, className);
    };

    $.removeClass = function(el, className) {
      return el.classList.remove(className);
    };

    $.toggleClass = function(el, className, value) {
      return el.classList.toggle(className, value);
    };

    $.hasClass = function(el, className) {
      return el.classList.contains(className);
    };

    $.css = function(el, prop, val) {
      return el.style[prop] = val;
    };

    return $;

  })();

  module.exports = $;

}).call(this);
