// Generated by CoffeeScript 1.6.3
(function() {
  var $, Keychain, input, _i, _len, _ref;

  global.document = document;

  global.Backbone = Backbone;

  global._ = _;

  $ = require('./js/dom');

  Keychain = require('../js/keychain');

  window.App = {
    Views: require('./js/views'),
    state: {}
  };

  window.keychain = new Keychain();

  window.main = new App.Views.Main(keychain);

  keychain.event.on('unlock', function() {
    return console.log('Keychain unlocked');
  });

  keychain.event.on('lock:after', function() {
    return console.log('Keychain has been locked');
  });

  keychain.load('../data/sample.cloudkeychain', function(err) {
    if (err != null) {
      return log(err);
    }
  });

  App.state.focus = false;

  _ref = $.tag('input');
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    input = _ref[_i];
    input.addEventListener('focus', function() {
      return App.state.focus = true;
    });
    input.addEventListener('blur', function() {
      return App.state.focus = false;
    });
  }

}).call(this);
